/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package TampilanData;

import javax.swing.*;
import java.util.Date;
import javax.swing.SpinnerDateModel;
import java.util.Calendar;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author ACER
 */
public class InsertAbsensi extends javax.swing.JDialog {

    /**
     * Creates new form InsertAbsensi
     */
    public InsertAbsensi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadKaryawanToComboBox();
        setLocationRelativeTo(parent);
    }

    private TampilanGui parentFrame;

    public InsertAbsensi(TampilanGui parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadKaryawanToComboBox();
        setLocationRelativeTo(parent);
        this.parentFrame = parent;

    }

    private void loadKaryawanToComboBox() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("HariKelimaPU");
        EntityManager em = emf.createEntityManager();

        try {
            List<Karyawan> listKaryawan = em.createQuery("SELECT n FROM Karyawan n", Karyawan.class).getResultList();
            IDK.removeAllItems();

            for (Karyawan n : listKaryawan) {
                IDK.addItem(n.getIdkaryawan());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data karyawan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            em.close();
            emf.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        IDA = new javax.swing.JTextField();
        IDK = new javax.swing.JComboBox<>();
        tgl = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        SpinnerDateModel sm = new SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR_OF_DAY);
        masuk = new javax.swing.JSpinner(sm);
        SpinnerDateModel sm2 = new SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR_OF_DAY);
        keluar = new javax.swing.JSpinner(sm2);

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID Absensi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("INSERT ABSENSI");

        jLabel3.setText("ID Karyawan");

        jLabel5.setText("Tanggal");

        jLabel6.setText("Jam Masuk");

        jLabel7.setText("Jam Keluar");

        IDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDKActionPerformed(evt);
            }
        });

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JSpinner.DateEditor de = new JSpinner.DateEditor(masuk, "HH:mm");
        masuk.setEditor(de);

        JSpinner.DateEditor de2 = new JSpinner.DateEditor(keluar, "HH:mm");
        keluar.setEditor(de2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(IDA))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(masuk, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(keluar))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(IDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(IDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5))
                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("HariKelimaPU");
            EntityManager em = emf.createEntityManager();

            String idAbsensi = IDA.getText().trim();
            String idKaryawan = (String) IDK.getSelectedItem();
            java.util.Date tanggal = tgl.getDate();

            java.util.Date jamMasukUtil = (java.util.Date) masuk.getValue();
            java.util.Date jamKeluarUtil = (java.util.Date) keluar.getValue();

            java.sql.Time jamMasuk = new java.sql.Time(jamMasukUtil.getTime());
            java.sql.Time jamKeluar = new java.sql.Time(jamKeluarUtil.getTime());

            if (idAbsensi.isEmpty() || idKaryawan == null || tanggal == null) {
                JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Absensi a = new Absensi();
            a.setIdabsensi(idAbsensi);
            a.setTanggal(new java.sql.Date(tanggal.getTime()));
            a.setJamMasuk(jamMasuk);
            a.setJamKeluar(jamKeluar);

            Karyawan k = em.find(Karyawan.class, idKaryawan);
            if (k == null) {
                JOptionPane.showMessageDialog(this, "ID Karyawan tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            a.setIdkaryawan(k);

            em.getTransaction().begin();
            em.persist(a);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Data absensi berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            if (parentFrame != null) {
                parentFrame.tampilkanDataAbsensi();
            }

            dispose();

            em.close();
            emf.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDKActionPerformed
        String selectedId = (String) IDK.getSelectedItem();
        if (selectedId == null) {
            return;
        }

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("HariKelimaPU");
        EntityManager em = emf.createEntityManager();

        try {
            Karyawan k = em.find(Karyawan.class, selectedId);
            if (k == null) {
                JOptionPane.showMessageDialog(this,
                        "ID Karyawan tidak ditemukan di database!",
                        "Peringatan", JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_IDKActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDA;
    private javax.swing.JComboBox<String> IDK;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSpinner keluar;
    private javax.swing.JSpinner masuk;
    private com.toedter.calendar.JDateChooser tgl;
    // End of variables declaration//GEN-END:variables
}
