/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TampilanData;

import TampilanData.Absensi;
import TampilanData.Karyawan;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MS
 */
public class TampilanGui extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;
    PreparedStatement pstmt = null;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/Indomaret";
    String user = "postgres";
    String password = "1234";
    private Object Tabel;

    /**
     * Creates new form TampilanGui
     */
    public TampilanGui() {
        initComponents();
        tampilkanData();
        tampilkanDataAbsensi();
    }

    public void tampilkanData() {
        EntityManager em = Persistence.createEntityManagerFactory("HariKelimaPU").createEntityManager();

        TypedQuery<Karyawan> q = em.createNamedQuery("Karyawan.findAll", Karyawan.class);
        List<Karyawan> hasil = q.getResultList();

        DefaultTableModel tbn = new DefaultTableModel(
                new String[]{"ID KARYAWAN", "NAMA", "ALAMAT", "GENDER", "SHIFT"}, 0
        );

        for (Karyawan data : hasil) {
            Object[] baris = new Object[5];
            baris[0] = data.getIdkaryawan();
            baris[1] = data.getNama();
            baris[2] = data.getAlamat();
            baris[3] = data.getGender();
            baris[4] = data.getShift();
            tbn.addRow(baris);
        }

        tabel.setModel(tbn);
        em.close();
    }

    public void tampilkanDataAbsensi() {
        EntityManager em = Persistence.createEntityManagerFactory("HariKelimaPU").createEntityManager();

        TypedQuery<Absensi> q = em.createNamedQuery("Absensi.findAll", Absensi.class);
        List<Absensi> hasil = q.getResultList();

        DefaultTableModel tbn = new DefaultTableModel(
                new String[]{"ID ABSENSI", "NAMA KARYAWAN", "TANGGAL", "JAM MASUK", "JAM KELUAR"}, 0
        );

        java.text.SimpleDateFormat sdfTanggal = new java.text.SimpleDateFormat("yyyy-MM-dd");
        java.text.SimpleDateFormat sdfWaktu = new java.text.SimpleDateFormat("HH:mm");

        for (Absensi data : hasil) {
            Object[] baris = new Object[5];
            baris[0] = data.getIdabsensi();
            baris[1] = data.getIdkaryawan().getNama();
            baris[2] = data.getTanggal() != null ? sdfTanggal.format(data.getTanggal()) : "";
            baris[3] = data.getJamMasuk() != null ? sdfWaktu.format(data.getJamMasuk()) : "";
            baris[4] = data.getJamKeluar() != null ? sdfWaktu.format(data.getJamKeluar()) : "";
            tbn.addRow(baris);
        }

        tabel1.setModel(tbn);
        em.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simpan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tabpane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        simpan.setText("Insert");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("Data Karyawan");

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Upload");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, "", null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IDKaryawan", "Nama", "Alamat", "Gender", "Shift"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        tabpane.addTab("Karyawan", jScrollPane1);

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Absensi", "ID Karyawan", "Tanggal", "Jam Masuk", "Jam Keluar"
            }
        ));
        tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel1);

        tabpane.addTab("Absen", jScrollPane2);

        jButton5.setText("Download");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(tabpane))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabpane, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        int index = tabpane.getSelectedIndex();
        String title = tabpane.getTitleAt(index);

        if (title.equals("Karyawan")) {
            InsertDialog dialog = new InsertDialog(this, true);
            dialog.setVisible(true);
        } else if (title.trim().equals("Absen")) {
            InsertAbsensi dialog2 = new InsertAbsensi(this, true);
            dialog2.setVisible(true);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int index = tabpane.getSelectedIndex();
        String title = tabpane.getTitleAt(index);

        if (title.equals("Absen")) {
            int baris = tabel1.getSelectedRow();
            if (baris >= 0) {
                String idAbsensi = tabel1.getValueAt(baris, 0).toString();
                String namaKaryawan = tabel1.getValueAt(baris, 1).toString();
                String tanggal = tabel1.getValueAt(baris, 2).toString();
                String jamMasuk = tabel1.getValueAt(baris, 3).toString();
                String jamKeluar = tabel1.getValueAt(baris, 4).toString();

                UpdateAbsen dialog1 = new UpdateAbsen(this, true, idAbsensi, namaKaryawan, tanggal, jamMasuk, jamKeluar);
                dialog1.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Pilih data absensi terlebih dahulu!");
            }
        } else if (title.equals("Karyawan")) {
            int baris = tabel.getSelectedRow();
            if (baris >= 0) {
                String IDK = tabel.getValueAt(baris, 0).toString();
                String nama = tabel.getValueAt(baris, 1).toString();
                String alamat = tabel.getValueAt(baris, 2).toString();
                String gender = tabel.getValueAt(baris, 3).toString();
                String shift = tabel.getValueAt(baris, 4).toString();

                UpdateDialog dialog2 = new UpdateDialog((java.awt.Frame) this, true,
                        IDK, nama, alamat, gender, shift);
                dialog2.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih data karyawan terlebih dahulu!");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int index = tabpane.getSelectedIndex();
        String title = tabpane.getTitleAt(index);

        if (title.equals("Karyawan")) {
            int baris = tabel.getSelectedRow();
            if (baris >= 0) {
                String idKaryawan = tabel.getValueAt(baris, 0).toString();
                DeleteDialog dialog = new DeleteDialog(this, true, idKaryawan);
                dialog.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih data karyawan dulu!");
            }

        } else if (title.equals("Absen")) {
            int baris = tabel1.getSelectedRow();
            if (baris >= 0) {
                String idabsensi = tabel1.getValueAt(baris, 0).toString();
                DeleteAbsensi dialog1 = new DeleteAbsensi(this, true, idabsensi);
                dialog1.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih data absensi dulu!");
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        try {
            int row = tabel.getSelectedRow();
            if (row >= 0) {

                String idKaryawan = tabel.getValueAt(row, 0).toString();
                String nama = tabel.getValueAt(row, 1).toString();
                String alamat = tabel.getValueAt(row, 2).toString();
                String gender = tabel.getValueAt(row, 3).toString();
                String shift = tabel.getValueAt(row, 4).toString();
            } else {
                JOptionPane.showMessageDialog(this, "Pilih data karyawan terlebih dahulu!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saat memilih data: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_tabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int index = tabpane.getSelectedIndex();
        String title = tabpane.getTitleAt(index);

        String reportPath = "";

        if (title.equalsIgnoreCase("Karyawan")) {
            reportPath = "C:\\Users\\ACER\\NetBeansProjects\\HariSembilan\\Hariempat\\src\\TampilanData\\DataKaryawan.jasper";
        } else if (title.equalsIgnoreCase("Absen")) {
            reportPath = "C:\\Users\\ACER\\NetBeansProjects\\HariSembilan\\Hariempat\\src\\TampilanData\\DataAbsensi.jasper";
        } else {
            JOptionPane.showMessageDialog(this, "Tab tidak memiliki laporan.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            Class.forName("org.postgresql.Driver");
            java.sql.Connection conn = java.sql.DriverManager.getConnection(
                    "jdbc:postgresql://localhost:5432/Indomaret",
                    "postgres",
                    "1234"
            );

            JasperReport reports = (JasperReport) JRLoader.loadObjectFromFile(reportPath);
            java.util.Map<String, Object> parameters = new java.util.HashMap<>();
            JasperPrint jprint = JasperFillManager.fillReport(reports, parameters, conn);

            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);

            conn.close();

        } catch (Exception ex) {
            Logger.getLogger(TampilanGui.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan saat mencetak laporan:\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int index = tabpane.getSelectedIndex();
        String title = tabpane.getTitleAt(index);

        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File filePilihan = jfc.getSelectedFile();
        System.out.println("File dipilih: " + filePilihan.getAbsolutePath());

        BufferedReader br = null;
        EntityManagerFactory emf = null;
        EntityManager em = null;

        try {
            br = new BufferedReader(new FileReader(filePilihan));
            emf = Persistence.createEntityManagerFactory("HariKelimaPU");
            em = emf.createEntityManager();

            em.getTransaction().begin();

            String baris;
            int berhasil = 0, gagal = 0;
            boolean skipHeader = true;

            while ((baris = br.readLine()) != null) {

                if (skipHeader) {
                    skipHeader = false;
                    continue;
                }

                if (baris.trim().isEmpty()) {
                    continue;
                }

                // Deteksi pemisah otomatis
                String pemisah = ";";
                if (baris.contains(",")) {
                    pemisah = ",";
                }
                if (baris.contains("\t")) {
                    pemisah = "\t";
                }

                String[] data = baris.split(pemisah);

                try {
                    if (title.equalsIgnoreCase("Karyawan")) {
                        if (data.length < 5) {
                            gagal++;
                            continue;
                        }

                        // Trim semua kolom
                        for (int i = 0; i < data.length; i++) {
                            data[i] = data[i].trim();
                        }

                        String id = data[0];
                        String nama = data[1];
                        String alamat = data[2];
                        String gender = data[3];
                        String shift = data[4];

                        if (id.isEmpty() || nama.isEmpty() || alamat.isEmpty() || gender.isEmpty() || shift.isEmpty()) {
                            gagal++;
                            continue;
                        }

                        if (em.find(Karyawan.class, id) != null) {
                            System.out.println("⚠️ Karyawan " + id + " sudah ada, dilewati.");
                            gagal++;
                            continue;
                        }

                        Karyawan k = new Karyawan();
                        k.setIdkaryawan(id);
                        k.setNama(nama);
                        k.setAlamat(alamat);
                        k.setGender(gender);
                        k.setShift(shift);

                        em.persist(k);
                        berhasil++;

                    } else if (title.equalsIgnoreCase("Absen")) {
                        if (data.length < 5) {
                            gagal++;
                            continue;
                        }

                        for (int i = 0; i < data.length; i++) {
                            data[i] = data[i].trim();
                        }

                        String idAbsensi = data[0];
                        String namaKaryawan = data[1];
                        String tanggalStr = data[2];
                        String jamMasukStr = data[3];
                        String jamKeluarStr = data[4];

                        if (idAbsensi.isEmpty() || namaKaryawan.isEmpty()
                                || tanggalStr.isEmpty() || jamMasukStr.isEmpty()
                                || jamKeluarStr.isEmpty()) {
                            gagal++;
                            continue;
                        }

                        // Ambil Karyawan berdasarkan nama
                        Karyawan karyawan = null;
                        try {
                            karyawan = em.createQuery(
                                    "SELECT k FROM Karyawan k WHERE k.nama = :nama", Karyawan.class)
                                    .setParameter("nama", namaKaryawan)
                                    .getSingleResult();
                        } catch (Exception e) {
                            System.out.println("⚠ Karyawan dengan nama " + namaKaryawan + " tidak ditemukan!");
                            gagal++;
                            continue;
                        }

                        try {
                            // Parsing tanggal & jam sesuai format CSV
                            SimpleDateFormat dateFormat;
                            if (tanggalStr.contains("/")) {
                                dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                            } else if (tanggalStr.contains("-")) {
                                dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                            } else {
                                throw new IllegalArgumentException("Format tanggal tidak dikenali: " + tanggalStr);
                            }
                            SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");

                            java.sql.Date sqlTanggal = new java.sql.Date(dateFormat.parse(tanggalStr).getTime());
                            java.sql.Time sqlJamMasuk = new java.sql.Time(timeFormat.parse(jamMasukStr).getTime());
                            java.sql.Time sqlJamKeluar = new java.sql.Time(timeFormat.parse(jamKeluarStr).getTime());

                            if (em.find(Absensi.class, idAbsensi) != null) {
                                System.out.println("Absensi " + idAbsensi + " sudah ada, dilewati.");
                                gagal++;
                                continue;
                            }

                            Absensi absensi = new Absensi();
                            absensi.setIdabsensi(idAbsensi);
                            absensi.setIdkaryawan(karyawan);
                            absensi.setTanggal(sqlTanggal);
                            absensi.setJamMasuk(sqlJamMasuk);
                            absensi.setJamKeluar(sqlJamKeluar);

                            em.persist(absensi);
                            berhasil++;

                        } catch (Exception eParse) {
                            System.out.println("Gagal memproses tanggal/jam pada baris: " + baris);
                            eParse.printStackTrace();
                            gagal++;
                            continue;
                        }
                    }

                } catch (Exception eRow) {
                    gagal++;
                    System.out.println("Gagal memproses baris: " + baris);
                    eRow.printStackTrace();
                }
            }

            em.getTransaction().commit();

            JOptionPane.showMessageDialog(null,
                    "Upload selesai!\nBerhasil: " + berhasil + "\nGagal: " + gagal);

            tampilkanData();
            tampilkanDataAbsensi();

        } catch (Exception ex) {
            ex.printStackTrace();
            if (em != null && em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
        } finally {
            try {
                if (br != null) {
                    br.close();
                }
            } catch (IOException e) {
            }
            if (em != null) {
                em.close();
            }
            if (emf != null) {
                emf.close();
            }
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel1MouseClicked


    }//GEN-LAST:event_tabel1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int index = tabpane.getSelectedIndex();
        String title = tabpane.getTitleAt(index);

        JTable table = null;

        if (title.equalsIgnoreCase("Karyawan")) {
            table = tabel;
        } else if (title.equalsIgnoreCase("Absen")) {
            table = tabel1;
        } else {
            JOptionPane.showMessageDialog(this,
                    "Tab ini tidak memiliki data untuk didownload.",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Simpan Data CSV");

        int result = chooser.showSaveDialog(this);
        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File file = chooser.getSelectedFile();

        String outputPath = file.getAbsolutePath();
        if (!outputPath.toLowerCase().endsWith(".csv")) {
            outputPath = outputPath + ".csv";
        }

        try (FileWriter fw = new FileWriter(outputPath)) {

            TableModel model = table.getModel();

            for (int i = 0; i < model.getColumnCount(); i++) {
                fw.write(model.getColumnName(i));

                if (i < model.getColumnCount() - 1) {
                    fw.write(";");
                }
            }
            fw.write("\n");

            for (int row = 0; row < model.getRowCount(); row++) {
                for (int col = 0; col < model.getColumnCount(); col++) {

                    Object value = model.getValueAt(row, col);

                    fw.write(value == null ? "" : value.toString());

                    if (col < model.getColumnCount() - 1) {
                        fw.write(";");
                    }
                }
                fw.write("\n");
            }

            JOptionPane.showMessageDialog(this,
                    "Download CSV berhasil!\n" + outputPath);

        } catch (IOException ex) {

            JOptionPane.showMessageDialog(this,
                    "Gagal download CSV:\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JTable tabel1;
    private javax.swing.JTabbedPane tabpane;
    // End of variables declaration//GEN-END:variables
}
