/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TampilanData;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import javax.swing.JFrame;

/**
 *
 * @author ACER
 */
public class Ubah extends javax.swing.JFrame {

    private String hashPassword(String password) {
        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("HariKelimaPU");
            byte[] hashed = md.digest(password.getBytes("UTF-8"));

            StringBuilder sb = new StringBuilder();
            for (byte b : hashed) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Creates new form Ubah
     */
    public Ubah(Login aThis) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pass1.setVisible(false);
        ubah.setVisible(false);
        pass.setVisible(false);
        cek.setVisible(false);
        lblsoal.setVisible(false);
        jawab1.setVisible(false);
        jawaban.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pass1 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        ubah = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblsoal = new javax.swing.JLabel();
        jawab1 = new javax.swing.JLabel();
        jawaban = new javax.swing.JTextField();
        cek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("UBAH");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Username :");

        pass1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pass1.setText("Password  Baru :");

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        cari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cari.setText("CARI");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        ubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ubah.setText("UBAH");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("KEMBALI");

        lblsoal.setText("-");

        jawab1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jawab1.setText("Jawaban :");

        cek.setText("Cek");
        cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(pass1)
                .addGap(18, 18, 18)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jawab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ubah)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jawaban, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsoal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(user, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cari)
                        .addGap(11, 11, 11))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cek)
                        .addGap(159, 159, 159))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari))
                .addGap(27, 27, 27)
                .addComponent(lblsoal)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jawaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jawab1))
                .addGap(18, 18, 18)
                .addComponent(cek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass1)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(ubah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        if (user.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Terlebih Dahulu");
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("HariKelimaPU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();

            String user1 = user.getText();
            Pw y = em.find(Pw.class, user1);

            if (y == null) {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                user.requestFocus();
            } else {
                lblsoal.setText(y.getPertanyaan());
                lblsoal.setVisible(true);
                jawab1.setVisible(true);
                jawaban.setVisible(true);
                cek.setVisible(true);
                user.setEditable(false);
                jawaban.requestFocus();
            }
            em.getTransaction().commit();
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_cariActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        if (pass.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password baru tidak boleh kosong!");
            return;
        }

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("HariKelimaPU");
        EntityManager em = emf.createEntityManager();

        em.getTransaction().begin();

        Pw akun = em.find(Pw.class, user.getText());

        akun.setPassword(pass.getText()); 

        em.getTransaction().commit();

        JOptionPane.showMessageDialog(this, "Password berhasil diubah!");

        em.close();
        emf.close();

        Login masuk= new Login();
        masuk.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_ubahActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        if (user.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi username dulu!");
        } else {
            cari.doClick();
        }
    }//GEN-LAST:event_userActionPerformed

    private void cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekActionPerformed
    if (jawaban.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jawaban tidak boleh kosong!");
            return;
        }

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("HariKelimaPU");
        EntityManager em = emf.createEntityManager();

        Pw userr = em.find(Pw.class, user.getText());

        if (userr == null) {
            JOptionPane.showMessageDialog(this, "User tidak ditemukan!");
            em.close();
            emf.close();
            return;
        }

        String inputJawaban = jawaban.getText().trim();
        String jawabanBenar = userr.getJawabanBenar().trim();

        if (inputJawaban.equalsIgnoreCase(jawabanBenar)) {
            JOptionPane.showMessageDialog(this, "Jawaban benar! Silakan buat password baru.");

            pass1.setVisible(true);
            pass.setVisible(true);
            ubah.setVisible(true);

            pass.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Jawaban salah!");
            jawaban.setText("");
            jawaban.requestFocus();
        }

        em.close();
        emf.close();
    }//GEN-LAST:event_cekActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JButton cek;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jawab1;
    private javax.swing.JTextField jawaban;
    private javax.swing.JLabel lblsoal;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel pass1;
    private javax.swing.JButton ubah;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
