/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package TampilanData;

import com.toedter.calendar.JDateChooser;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author ACER
 */
public class UpdateAbsen extends javax.swing.JDialog {

    /**
     * Creates new form UpdateAbsen
     */
    private TampilanGui parentFrame;

    public UpdateAbsen(TampilanGui parent, boolean modal, String ida, String idk, String tanggal, String jamMasuk, String jamKeluar) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

        this.parentFrame = parent;

        this.ida.setText(ida);
        this.ida.setName(ida);
        loadKaryawanToComboBox(idk);

        try {
            java.util.Date tglDate = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tanggal);
            this.tanggal.setDate(tglDate);

            java.text.SimpleDateFormat sdfJam = new java.text.SimpleDateFormat("HH:mm");
            this.masuk.setValue(sdfJam.parse(jamMasuk));
            this.keluar.setValue(sdfJam.parse(jamKeluar));

            this.masuk.setEditor(new JSpinner.DateEditor(this.masuk, "HH:mm"));
            this.keluar.setEditor(new JSpinner.DateEditor(this.keluar, "HH:mm"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadKaryawanToComboBox(String selectedId) {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("HariKelimaPU");
        EntityManager em = emf.createEntityManager();

        try {
            List<Karyawan> listKaryawan = em.createQuery("SELECT k FROM Karyawan k", Karyawan.class).getResultList();
            idk.removeAllItems();
            for (Karyawan k : listKaryawan) {
                idk.addItem(k.getIdkaryawan());
            }

            if (selectedId != null) {
                idk.setSelectedItem(selectedId);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data karyawan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            em.close();
            emf.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        ida = new javax.swing.JTextField();
        idk = new javax.swing.JComboBox<>();
        tanggal = new com.toedter.calendar.JDateChooser();
        SpinnerDateModel sm = new SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR_OF_DAY);
        masuk = new javax.swing.JSpinner(sm);
        SpinnerDateModel sm2 = new SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR_OF_DAY);
        keluar = new javax.swing.JSpinner(sm2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("UPDATE ABSEN");

        jLabel2.setText("ID ABSENSI");

        jLabel3.setText("ID KARYAWAN");

        jLabel4.setText("TANGGAL");

        jLabel5.setText("JAM MASUK");

        jLabel6.setText("JAM KELUAR");

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        idk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idkActionPerformed(evt);
            }
        });

        JSpinner.DateEditor de = new JSpinner.DateEditor(masuk, "HH:mm");
        masuk.setEditor(de);

        JSpinner.DateEditor de2 = new JSpinner.DateEditor(keluar, "HH:mm");
        keluar.setEditor(de2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(72, 72, 72))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(53, 53, 53)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(81, 81, 81)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(66, 66, 66)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(masuk)
                            .addComponent(keluar)
                            .addComponent(ida, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(update)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(ida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addComponent(idk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(update)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idkActionPerformed
        String selectedId = (String) idk.getSelectedItem();
        if (selectedId == null) {
            return;
        }

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("HariKelimaPU");
        EntityManager em = emf.createEntityManager();

        try {
            Karyawan k = em.find(Karyawan.class, selectedId);
            if (k == null) {
                JOptionPane.showMessageDialog(this,
                        "ID Karyawan tidak ditemukan di database!",
                        "Peringatan", JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_idkActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String oldId = ida.getName();
        String newId = ida.getText().trim();

        if (newId.isEmpty()
                || idk.getSelectedItem() == null
                || tanggal.getDate() == null
                || masuk.getValue() == null
                || keluar.getValue() == null) {

            JOptionPane.showMessageDialog(this,
                    "Semua field harus diisi!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("HariKelimaPU");
        EntityManager em = emf.createEntityManager();

        try {
            em.getTransaction().begin();

            Absensi cek = em.find(Absensi.class, newId);
            if (cek != null && !newId.equals(oldId)) {
                JOptionPane.showMessageDialog(this,
                        "ID Absensi sudah digunakan, pilih ID lain!",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                em.getTransaction().rollback();
                return;
            }

            Absensi absenLama = em.find(Absensi.class, oldId);
            if (absenLama == null) {
                JOptionPane.showMessageDialog(this,
                        "ID Absensi lama tidak ditemukan!",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                em.getTransaction().rollback();
                return;
            }

            String idKaryawanStr = (String) idk.getSelectedItem();
            Karyawan k = em.find(Karyawan.class, idKaryawanStr);
            if (k == null) {
                JOptionPane.showMessageDialog(this,
                        "ID Karyawan tidak ditemukan!",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                em.getTransaction().rollback();
                return;
            }

            em.remove(absenLama);
            em.flush();

            Absensi absenBaru = new Absensi();
            absenBaru.setIdabsensi(newId);
            absenBaru.setIdkaryawan(k);
            absenBaru.setTanggal(new java.sql.Date(tanggal.getDate().getTime()));
            absenBaru.setJamMasuk(new java.sql.Time(((Date) masuk.getValue()).getTime()));
            absenBaru.setJamKeluar(new java.sql.Time(((Date) keluar.getValue()).getTime()));

            em.persist(absenBaru);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this,
                    "Data absensi berhasil diupdate!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

            if (parentFrame != null) {
                parentFrame.tampilkanDataAbsensi();
            }

            dispose();

        } catch (Exception e) {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan saat update: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ida;
    private javax.swing.JComboBox<String> idk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner keluar;
    private javax.swing.JSpinner masuk;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
